services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      NEXT_TELEMETRY_DISABLED: "1"
      # Improves file watching on some Docker Desktop/WSL setups:
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
    volumes:
      # Mount your source
      - .:/app:delegated
      # Keep node_modules in the container (prevents host OS conflicts)
      - node_modules:/app/node_modules
      # Persist Next.js cache between restarts for faster HMR/rebuilds
      - next_cache:/app/.next
    # Re-run dev using the detected package manager inside the container
    command: >
      bash -lc '
      if [ -f pnpm-lock.yaml ]; then corepack enable && pnpm dev;
      elif [ -f yarn.lock ]; then corepack enable && yarn dev;
      else npm run dev; fi
      '
    # Optional: healthcheck to know when dev server is up
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  node_modules:
  next_cache:
